FROM scratch

COPY service /service

ARG POSTGRES_CONFIG
ARG POSTGRES_CONFIG_TESTING

ENV POSTGRES_CONFIG=$POSTGRES_CONFIG
ENV POSTGRES_CONFIG_TESTING=$POSTGRES_CONFIG_TESTING

EXPOSE 80 5432

CMD ["/service"]